make:
	gcc -Wall -c main.c
	gcc main.o -o main

clean:
	rm -f *.so *.o *.a

test:
	make
	./main abc@agh.com rekrutacja zostałpanstudentem
	./main zzz@agh.com aaaaaaa aaaaaa
	./main bielowka halo halohalo
	./main bielowka@localhost halo halohalo2
	./main nadawca
	./main data
	make clean

